### ISSUE TITLE
output vcf file has malformed header

### ISSUE THREAD

**Issue by imsarath** [vpc-ccg/svict#10]
Hi,

I tried svict on my cfDNA sample. while trying to use svict output vcf file for downstream analysis(IGV), I got this error as `Your input file has a malformed header: there are not enough columns present in the header line: #CHROM  POS ID  REF ALT QUAL  FILTER  INFO,`

The header line is separated by spaces instead of tab.

Thanks,

**Comment by yenyilin** [comment]
We will resolve it in the next few days and push it to the github.

**Comment by yenyilin** [comment]
Should be fixed in v1.0.1. Please give it a try and let us know if you have any concerns.
