### ISSUE TITLE
Core dump issue

### ISSUE THREAD

**Issue by tahuh** [vpc-ccg/svict#8]
Hi, I have read paper of SViCT and tried to use this tool for my analysis

The compilation was successful and ran this tool using cfDNA sample and the core dump has raised.

Command line I have used is shown below

`
$SVICT/svict -i sample.bam -r hg38.fa -o outfile
`
The GDB's strack trace using core file generated shown below
`
#0  0x000000000042eddc in svict_caller::generate_intervals(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool) ()
(gdb) bt
#0  0x000000000042eddc in svict_caller::generate_intervals(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool) ()
#1  0x0000000000436b60 in svict_caller::run(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int, int, int, int, int, int, bool, int, int, int, double, bool, bool) ()
#2  0x0000000000409d3b in predict(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool, bool, int, int, int, int, int, int, int, int, int, bool, int, int, int, double, bool, bool, bool) ()
#3  0x0000000000404a4c in main ()
`

The computer is equipped with Ubuntu 16,04 LTS and 32 cores of Xeon Phi system.
Our compiler is gcc 5.4.0
The reference sequence I have used is GRCh38 version

Thanks ins advance

**Comment by fhach** [comment]
We are looking into this. Please keep tuned.

**Comment by yenyilin** [comment]
We pinpoint the issue. We will resolve it in the next few days and push it once tested. Thanks.

**Comment by yenyilin** [comment]
Should be fixed in v1.0.1. Please let us know if you still experience similar issues.
